data:
  data_set: icvl_dataset
  train_dir: data/icvl_dataset/train_dataset
  valid_dir: data/icvl_dataset/valid_dataset
  source_dir: data/source_dataset/NAS_source
  norm: channel_max  # 1.fixed_max 2.channel_max  3.global_max
  fixed: None  # fixed_max要提供这个值  channel_max与global_max设置为None

train:
  model: Res2Unet_32w6s_nointerp
  max_epochs: 5000
  batch_size: 2
  learning_rate: 0.0001
  device: cuda:0
  optimizer: Adam
  pre_train: None #pth/MSFAUnet/epoch-150-psnr-29.37531-sam-0.06144-10-27.pth #pth/scrbV7/epoch-470-psnr-30.03404-sam-0.06166-10-19.pth
  loss_function:
    losses: ['L1Loss', 'MSELoss', 'MARELoss']       # Mean Absolute Error, L1Loss
    weights: [0.99, 0.0, 0.01]
  sigmoid_scale: 1.001   # fixed_max为1.0  channel_max 与 global_max最好设置大一点1.001来满足最大值与真实值的差距
  is_interp: False
  is_two_x: False

evaluate:
  evaluation_metrics: ['PSNR', 'SAM']
  early_stopping:
    patience: 50
    monitor: ['PSNR', 'SAM']
  batch_size: 2

test:
  model: EHANnet #Res2Unet_PPIG #MSFAUnet_baseV2 #Base_SCRBnet
  data_set: 原_长焦室外
  test_dir: test_data/原_长焦室外 #test_data/原_车道 #test_data/原_花 #data/icvl_dataset/valid_dataset # data/icvl_dataset/valid_dataset #
  recovered_dir: test_data/重构_长焦室外 #test_data/重构_车道 #test_data/重构_花 #recovered_icvl #  data/recovered_icvl #
  device: cuda:0
  pre_train: pth/EHANnet/4_0,0001_0,99_0,0_0,01_nas_dataset_12_26/EHANnet-best-epoch-1665-psnr-29.04807-sam-0.07679-12-27.pth #pth/Res2Unet_baseV2_PPIG/2_0,0001_0,99_0,0_0,01_nas_dataset/Res2Unet_baseV2_PPIG-best-epoch-4325-psnr-32.69435-sam-0.05040-12-19.pth #pth/MSFAUnet_32w6s_nointerp/best-epoch-614-psnr-31.90132-sam-0.05131-11-11.pth # # pth/base_scrb/best-epoch-2021-psnr-30.88285-sam-0.06006-10-26.pth #pth/MSFAUnet_32w6s_nointerp/best-epoch-614-psnr-31.90132-sam-0.05131-11-11.pth #pth/Res2Unet_baseV2_PPIG/2_0,0001_0,99_0,0_0,01_nas_dataset/Res2Unet_baseV2_PPIG-best-epoch-4325-psnr-32.69435-sam-0.05040-12-19.pth
  norm: channel_max
  fixed: None
  sigmoid_scale: 1.001
  log: log_channel_max_nas/test_log

log:
  log_dir: log_channel_max_nas/log
  ckp_dir: log_channel_max_nas/checkpoint
  save_frequency: 10

dataset: MosaicDataset_enhance

random_seed: 20231226
